### ISSUE TITLE
Create man page for statusbar config 

### ISSUE THREAD

**Issue by Philipp6802** [DHBW-FN/OxideWM#139]
New users will neccessarily come in contact with our config file. 
Even though our config **should be well annotated** and adjacent tutorial for new user might be very welcome.

# Possible implementation options
* Part of the general user manual
* Part of the man page
* Separate man page
* part of the config file (as comment)

**Comment by gungula** [comment]
Please use the unified formatting for linux manpages like e. g. described [here](https://linux.die.net/man/1/i3) (Name, Synopsis, maybe Options, ...).

**Comment by gungula** [comment]
closed with pr #207
