### ISSUE TITLE
Change workspace behavior

### ISSUE THREAD

**Issue by FelixSchladt** [DHBW-FN/OxideWM#147]
I tried using our current main branch and I dont think the way workspaces are setup rn is a good idea.

I think we could greatly reduce the current complexity and make it more usable at the same time:

# I personally think only the following commands are needed
1. `GoToWorkspace`
2. `MoveToWorkspace`
3. `MoveToWorkspaceAndFollow` -> See at Chapter `Special behavior` why this is required as standalone command

# In our current setup we have dynamic workspaces: 
* If the workspace is empty and not selected -> remove this workspace
* If I go to a workspace that does not exists -> create this workspace
* If I move a window to a workspace that does not exist -> create the workspace

=> Other behavior is in my opinion really confusing and does not fit in with the dynamic workspace philosophy.
I personally think this dynamic approach is something that is quite unique among window managers and I think its a cool concept we should stick with. 

# Some special behavior I would propose:
## `Next` and `Previous`
* GoToWorkspace -> The next/previous created workspace is selected. If none exist -> create a new one
* MoveToWorkspace -> The window is moved to the next/previous created workspace. If none exist -> create a new one

## `New` additional Argument to next previous number
I think this would be really cool. The idea is to get a new free workspace without selecting a number.
* `GoToWorkspace` -> The next free index is taken and a new workspace create and selected
* `MoveToWorkspace` -> The window is moved to next not used index and placed on this new workspace

## Why `MoveToWorkspaceAndFollow` is required
In the case the user uses `next`, `previous` or `new` as argument command chaining becomes very difficult as the context gets lost after the first executed command. We would either need to remember this context or as add `MoveToWorkspaceAndFollow` as its own command to prevent this.

I would like to have a discussion about this behavior and get your input. 

I would propose to include as part of this article a manual describing our behavior in detail for the manual /docs /manpages.

# DoD:
* Discuss behavior
* Implement behavior
* Write documentation

**Comment by janschaible** [comment]
> If the workspace is empty and not selected -> remove this workspace

I would not do this, what if the user opens the workspace to put windows on later ??

**Comment by janschaible** [comment]
A + Zahl goto
A+S+Zahl MoveToWSAndFollow
A+C+Zahl MoveTo 
A+n new empty ws
A+S+new Moetofollo
