### ISSUE TITLE
wrong time in error message output

### ISSUE THREAD

**Issue by gungula** [DHBW-FN/OxideWM#166]
## Found in
    
- 743cfb8310410b2dd0bdce3043f7f198ea47b103

## Description

When receiving an error message in the command prompt the clock is one hour late.
```bash
2023-02-03 **21:55:31** - [ERROR]: [...]
```

**Comment by FelixSchladt** [comment]
I would expect this to be related to utc

**Comment by janschaible** [comment]
I can not recreate this error on my system ?? :)
