### ISSUE TITLE
create seperate deployed config file with meta(windows) key as main modifier

### ISSUE THREAD

**Issue by FelixSchladt** [DHBW-FN/OxideWM#180]
As the meta key is normally reserved for the running os this is a bad choice when debugging and testing as this would not work with xephyr. Thats the reason why ALT has been chosen so far. But I think the Meta key is the obvious choice for an production deployment. Therefore I would propose to create a seperate debug and production config with different keyboard shortcuts. 
Further I would like to put the META key as default key in any documentation.

This especially refers to @Philipp6802 and his #34 #97 issues.

**Comment by Philipp6802** [comment]
I created the file meta_config.yml on my doc/ISSUE97 branch

**Comment by gungula** [comment]
implemented meta in default config.yml

**Comment by Philipp6802** [comment]
Looks like these changes were reverted because of some pull request issues
