### ISSUE TITLE
when sending ipc message execute, command fullscreen is executed

### ISSUE THREAD

**Issue by janschaible** [DHBW-FN/OxideWM#186]
# <Name of the bug> <- This should be the issue title

## Found in
    
b5d6ff53afd18269486dc807921805fd65a70fd3

## Description

when sending ipc message execute, command fullscreen is executed

### Steps to reproduce
- open window manager
- send ipc message execute
- fullscreen command is executed

## Comments

**Comment by FelixSchladt** [comment]
fixed
