### ISSUE TITLE
create presentation

### ISSUE THREAD

**Issue by gungula** [DHBW-FN/OxideWM#192]
Create a presentation for summing up the project.
Presentation should last around 15 mins.

Points open for clarification:
- focus: technical side of Oxide or rather documentation / management ...

Please feel free to add your ideas / questions!

**Comment by B1TC0R3** [comment]
I would like to take a few minutes explaining the different testing methods and showing out automated testing framework.
I figure this would take about 5 minutes.
Let me know if there is time for this.

**Comment by gungula** [comment]
@B1TC0R3 Yes, sounds good. I guess about 5 minutes is a good range.

**Comment by FelixSchladt** [comment]
https://www.canva.com/design/DAFaKMwyuD0/6jlVxJrTcNbVF0ZUP9652g/edit?utm_content=DAFaKMwyuD0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by FelixSchladt** [comment]
done
