### ISSUE TITLE
No shell refresh after cargo install

### ISSUE THREAD

**Issue by janschaible** [DHBW-FN/OxideWM#201]
## Found in
    
- 94567e8e909b0fc90ba3bb097879c78895dcfcbd

## Description

i guess since the path variable is modified during installation of rust, cargo is still unknown when we try to compile oxide direct after installation, after quitting and restarting terminal, oxide builds as expected

**Comment by B1TC0R3** [comment]
The reason for this issue was a missing `source` statement in front of the `export` call.
It should be fixed now.
