### ISSUE TITLE
Closing windows with oxide-ipc closes dbus connection

### ISSUE THREAD

**Issue by B1TC0R3** [DHBW-FN/OxideWM#209]
## Found in
    
- d1bd295e8c326dbbd8ea750a4aae27cf594ffdc5

## Description

When closing a window in Xephyr with the command
```bash
oxide-msg -c kill
```
the focused window closes, but the IPC-connection is not usable afterwards.
Any other `oxide-msg` call receives the same error message that occurs when `oxide` is not running at all.
In this case, `oxide` is still working, but the connection is failing.

## Comments

This Bug also is blocking some automated tests from completing.

**Comment by FelixSchladt** [comment]
Your command doenst make any sense to me. This is not the right syntax for oxide-msg

```sh
oxide-msg --exec kill
error: Found argument '--exec' which wasn't expected, or isn't valid in this context

Usage: oxide-msg [OPTIONS] --command <COMMAND>

For more information try '--help'
```

To kill the current window:
```
oxide-msg -c kill
```

**Comment by B1TC0R3** [comment]
Yes, I am using that command in the testing script, I just typed it incorrectly on here.
I fixed that issue.

This unfortunately changes nothing about this issue, as I can only still close a single window before the window closes.
Can I ask that you may run the tests on your machine to see what happens?

For the mean time, I have moved the validation of this function over to the manual tests, where it works perfectly fine with keybinds.
