### ISSUE TITLE
Window focus can not be changed with keyboard

### ISSUE THREAD

**Issue by B1TC0R3** [DHBW-FN/OxideWM#213]
## Found in
    
- e702a138ec420bbdeb6012bb2327f10b122135ee

## Description

Neither when using Xephyr nor when using the full install can I use the keyboard to change window focus.
The mouse does work, but as soon as it is not hovering above any window, I have no focus at all.
In addition, trying to change focus when no window is selected seems to close the IPC connection.

## Comments

While I am looking into potential reasons for this bug further, I would like to ask
@FelixSchladt and @janschaible whether you two can see the same behavior 
on your installations.
Is this intended functionality?

**Comment by FelixSchladt** [comment]
I tested this on my system and focus changing via the keyboard as well as ipc works perfectly well. Is you setup maybe broken somehow?

This is not the first issue from you I cannot reproduce. Could you maybe otherwise get at least some more information on where and what fails?

**Comment by B1TC0R3** [comment]
Thank you for your feedback. Here's a little bit of information while I debug this issue further:

> Is your setup maybe broken somehow?

Unlikely, I use the current main version, merged over to my testing branch.
I will, however, try this again after the most recent changes.

> This is not the first issue from you I cannot reproduce. Could you maybe otherwise get at least some more information on where and what fails?

I would not know how to, since it literally just does not get a focus on any window while I do not have my mouse hovering over it. I was, however, able to get the focusing to work by moving my mouse over a window and then off again.
This is still not perfect, but it does work for the time being.

> ahh btw I tried reproducing on the current main, I dont know what commit hash that is you mentioned above

The commit hash is from branch `test/ISSUE92-automated`. I thought it would automatically link to that branch if you click on it.

Generally, if it is working fine for all of you, I would not consider this too much of a problem personally, but I would like to look into it a bit regardless.
