### ISSUE TITLE
Automated Tests

### ISSUE THREAD

**Issue by B1TC0R3** [DHBW-FN/OxideWM#92]
This branch will server as a long term hub for everything that is related to automated testing.

If you find any bugs yourself, please report them here: [Bug Reports](https://github.com/DHBW-FN/OxideWM/issues/93).

**Comment by B1TC0R3** [comment]
No, things like that belong right here ^_^

**Comment by B1TC0R3** [comment]
The test has been written, it is failing.

**Comment by janschaible** [comment]
Why did i close this, does it get closed, when the branch is merged ????

Anyway, regarding the `pub fn load_config_from_wrong_datatype_file()` shouldn't it fail, do we really want to default to some values ?:)
